project:
  type: website

website:
  title: "ISSS608 Group 12"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - text: Documentations
        menu:
        - text: Project Proposal (Revised)
          href: proposal_revised.qmd
        - text: Project Proposal (Initial)
          href: proposal.qmd
        - text: Meeting Minutes 1
          href: Minutes/meeting_minutes_1.html
        - text: Meeting Minutes 2
          href: Minutes/meeting_minutes_2.html
        - text: Meeting Minutes 3
          href: Minutes/meeting_minutes_3.html
        - text: Meeting Minutes 4
          href: Minutes/meeting_minutes_4.html
      - text: Analysis
        menu:
        - text: Data Preparation
          href: data_prep.qmd
        - text: Exploratory Data Analysis (EDA)
          href: eda.qmd
        - text: Confirmatory Data Analysis (CDA)
          href: cda.qmd
        - text: Time Series Analysis 
          href: time_series.qmd

format:
  html:
    theme:
      - minty
      - brand
    css: styles.css
    toc: true

editor: visual

