project:
  type: website

website:
  title: "ISSS608 Group 12"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - text: Documentations
        menu:
        - text: Project Proposal
          href: proposal.qmd
        - text: Meeting Minutes 1
          href: Minutes/meeting_minutes_1.html
        - text: Meeting Minutes 2
          href: Minutes/meeting_minutes_2.html
        - text: Meeting Minutes 3
          href: Minutes/meeting_minutes_3.html
      - href: data_preparation.qmd
        text: Data Preparation

format:
  html:
    theme:
      - minty
      - brand
    css: styles.css
    toc: true

editor: visual

