project:
  type: website

website:
  title: "ISSS608 Group 12"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: proposal.qmd
        text: Project Proposal

format:
  html:
    theme:
      - minty
      - brand
    css: styles.css
    toc: true

editor: visual

