---
title: "Minutes of Meeting 4"
author: "Jia Peng Chua | Zanelle Lee Wenfang"
date-modified: "last-modified"
execute:
    echo: true
    eval: true
    warning: false
    freeze: true
---

## Date

19 MARCH 2025

## Time

8.30am - 9.30am

## Venue

Virtual (Teams)

## Meeting Attendance

-   Chua Jia Peng

-   Zanelle Lee Wenfang

-   Prof Kam Tin Seong

## Issues/Discussions

Discussion on dataset + steps forward with Prof Kam

To discuss:

1.  Dataset
2.  Project focus and possible areas to explore using dataset

## Points taken from consultation with Prof

-   Not a must to explore what senior did, who did extra work on geospatial. There’s another team's focus is on EDA. Not necessary to go into geospatial. There is sufficient data to go into EDA and CDA.

-   Locate and analyse outbreak during the few months of particular years

-   TIME SERIES

To use curve fitting or statistical curve since it is not a typical time series. Typical time series would usually look at recurrences. X axis to be time interval (weekly, epi week) and Y axis to be number of occurrences (i.e. number of dengue cases.)

Disease outbreak (spikes) will not be normal distribution. Can explore negative binomial, poisson, exponential distriutions and see which one fits best.

-   Dengue - monitor in epidemiological week (Epi Week). Lubridate - compute epi-week. To look at weekly data. Usually relatively short, should take note when it starts and when it starts to peak. Use time frame when event start, chopping the start and end (refer to hands on)

-   Taiwan is very careful with 3(?) diseases, dengue being one of them. Dengue is popular in equatorial zone. In recent years, dengue has spread to temperate zone. Taiwan is far from equatorial, and many people visit from these countries and leading to outbreak

-   There are some missing values and errors, e.g. no gender, GPS location, excluding a few of these is fine. Will not affect the entire results

-   Dengue tends to be more significant for foreigners' cases than locals. Locals tend to build up immune system. Foreigners' symptoms are more serious and tend to be confirmed cases. During the outbreak, can evaluate foreign carrier vs local spread.

-   2 major outbreaks in dataset (2015 and 2023 after viewing dataset), if no data means no cases (Taiwan case reporting is very detailed). Will need to look into background of Dengue and whether cases are spread via foreigners entering Taiwan (since Taiwan is not near the equator) and also look into the outliers by map location (some places have plenty of cases, some have just a few). Check during outbreak period if there are more foreigners or locals, look at the trends, peak periods (week/month).

-   Can allow users to play with ancillary data for SHINY app e.g. age, gender, local/foreigner, travelled recently, difference between local and imported cases etc. To also note that X-Y coordinate is a grid, which protects data of individuals.

## **Conclusion**

To do literature review:

-   epi week – JP

-   background info on TW + dengue – JP

-   foreigner vs local infection – Zan

-   curve fitting for time series – Zan

EDA:

-   General EDA – JP

-   EDA on 2015 and 2023 (outbreak periods) - Zan
